autoload:
  sfTwigPlugin_lib:
    name:           sfTwigPlugin_lib
    path:           <?php echo realpath(dirname(__FILE__).'/../lib')."\n" ?>
    recursive:      true
    exclude:        ['vendor']
